<option value="00">00 - AERO CRS</option>
<option value="02">02 - SearchArter</option>
<option value="03">03 - INVOLATUS</option>
<option value="0B">0B - BLUE AIR</option>
<option value="0C">0C - Cobra Aviation</option>
<option value="0D">0D - UNKNOWN</option>
<option value="0O">0O - STA TRAVEL</option>
<option value="0V">0V - VIETNAM AIR SERVICE</option>
<option value="1I">1I - NETJETS</option>
<option value="1L">1L - CitizenPlane</option>
<option value="1M">1M - SIRENA JSC</option>
<option value="1X">1X - BRANSON AIR EXPRESS</option>
<option value="2A">2A - DEUTSCHE BAHN</option>
<option value="2B">2B - ALBAWINGS</option>
<option value="2C">2C - SNCF</option>
<option value="2D">2D - EASTERN AIRLINES</option>
<option value="2E">2E - SMOKEY BAY AIR</option>
<option value="2F">2F - FAIR AVIATION</option>
<option value="2G">2G - ANGARA AIRLINES</option>
<option value="2H">2H - THALYS INTERNTIONAL</option>
<option value="2I">2I - STAR PERU</option>
<option value="2J">2J - AIR BURKINA</option>
<option value="2K">2K - AVIANCA ECUADOR</option>
<option value="2L">2L - HELVETIC</option>
<option value="2M">2M - MOLDAVIAN AIRLINES</option>
<option value="2N">2N - NEXTJET</option>
<option value="2O">2O - ISLAND AIR SERVICE</option>
<option value="2P">2P - PAL EXPRESS</option>
<option value="2R">2R - VIA RAIL CANADA</option>
<option value="2S">2S - Island Express</option>
<option value="2T">2T - TRUJET</option>
<option value="2U">2U - SUN DOR INTERNATIONAL AIRLINES</option>
<option value="2V">2V - AMTRAK</option>
<option value="2W">2W - World2Fly</option>
<option value="2X">2X - XEROX</option>
<option value="2Y">2Y - ULD RENTAL</option>
<option value="2Z">2Z - EXPRESS RAIL LINK SDN BHD</option>
<option value="3A">3A - CHU KONG PASSENGER TRANSPORT</option>
<option value="3B">3B - BINDER CABO VER</option>
<option value="3C">3C - AIR CHATHAMS</option>
<option value="3D">3D - DOKASCH</option>
<option value="3E">3E - AIR CHOICE ONE</option>
<option value="3F">3F - FLYONE ARMENIA Limited Liabili</option>
<option value="3G">3G - ASIA CARGO EXPRESS</option>
<option value="3H">3H - AIR INUIT</option>
<option value="3J">3J - ZIPAIR</option>
<option value="3K">3K - JETSTAR ASIA AIRWAYS</option>
<option value="3L">3L - Air Arabia Abu Dhabi</option>
<option value="3M">3M - SILVER AIRWAYS CORP</option>
<option value="3N">3N - AIR URGA</option>
<option value="3O">3O - AIR ARABIA MAROC</option>
<option value="3P">3P - TIARA AIR N.V. DBA TIARA AIR A</option>
<option value="3Q">3Q - KC INTERNATIONAL AIRLINES</option>
<option value="3R">3R - DIVI DIVI AIR</option>
<option value="3S">3S - AIR ANTILLES EXPRESS</option>
<option value="3T">3T - TARCO AIR</option>
<option value="3U">3U - SICHUAN AIRLINES</option>
<option value="3V">3V - ASL AIRLINES BELGIUM</option>
<option value="3W">3W - MALAWIAN AIRLINES</option>
<option value="3Z">3Z - TRAVEL SERVICE POLSKA</option>
<option value="4A">4A - CALIFORNIA PACIFIC</option>
<option value="4B">4B - BOUTIQUE AIR</option>
<option value="4C">4C - LATAM AIRLINES COLOMBIA</option>
<option value="4D">4D - AIR SINAI</option>
<option value="4G">4G - GAZPROMAVIA AVIATION COMPANY L</option>
<option value="4I">4I - IHY IZMIR HAVAYOLLARI</option>
<option value="4J">4J - JETAIR CARRIBEAN</option>
<option value="4K">4K - KENN BOREK AIR</option>
<option value="4L">4L - LAS S.A.</option>
<option value="4M">4M - LAN ARGENTINA</option>
<option value="4N">4N - AIR NORTH</option>
<option value="4O">4O - INTERJET</option>
<option value="4P">4P - REGIONAL SKY</option>
<option value="4Q">4Q - SAFI AIRWAYS</option>
<option value="4R">4R - HAMBURG INTERNATIONAL</option>
<option value="4S">4S - Red Sea Airlines</option>
<option value="4T">4T - TRANSWEST AIR</option>
<option value="4U">4U - GERMANWINGS</option>
<option value="4V">4V - BVI AIRWAYS</option>
<option value="4W">4W - WARBELOWS AIR VENTURES</option>
<option value="4X">4X - ATLANTIC EXPRESS AIRLINES</option>
<option value="4Y">4Y - EW DISCOVER</option>
<option value="4Z">4Z - SA AIRLINK</option>
<option value="5B">5B - BASSAKA AIR</option>
<option value="5D">5D - AEROMEXICO CONNECT</option>
<option value="5F">5F - FLYONE</option>
<option value="5G">5G - MAYAIR</option>
<option value="5H">5H - FIVE FORTY AVIATION</option>
<option value="5I">5I - ALSA GRUPO</option>
<option value="5J">5J - CEBU PACIFIC AIR</option>
<option value="5K">5K - HI FLY TRANSPORTES AEREOS</option>
<option value="5L">5L - FLY SALONE</option>
<option value="5M">5M - FLYMONTSERRAT</option>
<option value="5N">5N - JSC NORDAVIA REGIONAL AIRLINE</option>
<option value="5O">5O - ASL AIRLINES FRANCE</option>
<option value="5Q">5Q - HOLIDAY EUROPE</option>
<option value="5S">5S - SERVICIOS AEREOS PROFES</option>
<option value="5T">5T - CANADIAN NORTH</option>
<option value="5U">5U - TAG AIRLINES </option>
<option value="5V">5V - EVERTS</option>
<option value="5W">5W - WIZZ AIR ABU DHABI</option>
<option value="5Y">5Y - ATLAS AIR</option>
<option value="5Z">5Z - CEMAIR</option>
<option value="6A">6A - ARMENIA AIRWAYS</option>
<option value="6B">6B - TUIFLY NORDIC</option>
<option value="6C">6C - AIR TIMOR</option>
<option value="6D">6D - TRAVEL SERVICE SLOVENSKO</option>
<option value="6E">6E - INDIGO</option>
<option value="6G">6G - EXECUTIVE EXPRESS</option>
<option value="6H">6H - ISRAIR AIRLINES</option>
<option value="6I">6I - AIR ALSIE</option>
<option value="6J">6J - SOLASEED</option>
<option value="6K">6K - KYRGYZ TRANS AVIA LTD AIRLINE</option>
<option value="6L">6L - AKLAK AIR</option>
<option value="6N">6N - NIGER AIRLINES</option>
<option value="6O">6O - ORBEST</option>
<option value="6Q">6Q - CHAM WINGS AIRLINES</option>
<option value="6R">6R - ALROSA</option>
<option value="6S">6S - SAUDI GULF AIRLINES</option>
<option value="6V">6V - AVANZA</option>
<option value="6W">6W - SARATOV AIRLINES</option>
<option value="6X">6X - AMADEUS SIX</option>
<option value="6Y">6Y - SMARTLYNX AIRLINES</option>
<option value="6Z">6Z - JSC EURO-ASIA AIR</option>
<option value="7A">7A - EXPRESS AIR CARGO</option>
<option value="7B">7B - TRUE AVIATION</option>
<option value="7C">7C - JEJU AIR</option>
<option value="7D">7D - MADAGASIKARA AIRWAYS</option>
<option value="7E">7E - SYLT AIR GMBH</option>
<option value="7F">7F - FIRST AIR</option>
<option value="7G">7G - STARFLYER</option>
<option value="7H">7H - RAVN ALASKA</option>
<option value="7I">7I - INSEL AIR INTERNATIONAL</option>
<option value="7M">7M - MAP LINHAS AEREAS</option>
<option value="7N">7N - PAWA DOMINICANA</option>
<option value="7P">7P - AIR PANAMA</option>
<option value="7Q">7Q - ELITE AIRWAYS</option>
<option value="7R">7R - RUSLINE</option>
<option value="7T">7T - TRENITALIA</option>
<option value="7V">7V - FEDERAL AIRLINES</option>
<option value="7W">7W - WIND ROSE AVIATION CO</option>
<option value="7X">7X - AMADEUS SEVEN</option>
<option value="7Y">7Y - MANN YADANARPON AIRLINES</option>
<option value="7Z">7Z - Z AIR</option>
<option value="8A">8A - ARROW PANAMA</option>
<option value="8B">8B - TRANSNUSA AVIATION</option>
<option value="8C">8C - COTAI WATER JET</option>
<option value="8D">8D - SERVANT AIR</option>
<option value="8E">8E - BERING AIR</option>
<option value="8F">8F - STP AIRWAYS</option>
<option value="8G">8G - MID AFRICA AVIATION</option>
<option value="8H">8H - BH AIR</option>
<option value="8I">8I - INSEL AIR ARUBA</option>
<option value="8J">8J - LINEA AEREA ECO JET</option>
<option value="8L">8L - LUCKY AIR</option>
<option value="8M">8M - MYANMAR AIRWAYS</option>
<option value="8N">8N - REGIONAL AIR SERVICES</option>
<option value="8P">8P - PACIFIC COASTAL AIRLINES</option>
<option value="8Q">8Q - ONUR AIR</option>
<option value="8R">8R - REGOURD AVIATION</option>
<option value="8S">8S - TURBOJET</option>
<option value="8T">8T - AIR TINDI LTD</option>
<option value="8U">8U - AFRIQIYAH AIRWAYS</option>
<option value="8V">8V - WRIGHT AIR SERVICES</option>
<option value="8W">8W - FLY ALWAYS</option>
<option value="8Y">8Y - PAN PACIFIC AIRLINES</option>
<option value="8Z">8Z - CONGO AIRWAYS</option>
<option value="9B">9B - ACCESRAIL</option>
<option value="9C">9C - SPRING AIRLINES</option>
<option value="9D">9D - GENGHIS KHAN AIRLINES</option>
<option value="9E">9E - ENDEAVOR AIR</option>
<option value="9F">9F - EUROSTAR</option>
<option value="9G">9G - 9G RAIL</option>
<option value="9H">9H - CHANGAN AIRLINES</option>
<option value="9I">9I - ALLIANCE AIR</option>
<option value="9J">9J - DANA AIRLINES</option>
<option value="9K">9K - CAPE AIR</option>
<option value="9M">9M - CENTRAL MOUNTAIN AIR</option>
<option value="9N">9N - TROPIC AIR</option>
<option value="9P">9P - AIR ARABIA JORDAN</option>
<option value="9Q">9Q - CAICOS EXPRESS AIRWAYS</option>
<option value="9R">9R - SATENA</option>
<option value="9S">9S - SPRING AIRLINES</option>
<option value="9T">9T - ACT HAVAYOLLARI</option>
<option value="9U">9U - AIR MOLDOVA</option>
<option value="9V">9V - AVIOR</option>
<option value="9W">9W - JET AIRWAYS</option>
<option value="9X">9X - SOUTHERN AIRWAYS EXPRESS</option>
<option value="9Y">9Y - AIR KAZAKSTAN</option>
<option value="A0">A0 - BA Euroflyer</option>
<option value="A1">A1 - G2 SWITCH WORKS</option>
<option value="A2">A2 - Anima Wings</option>
<option value="A3">A3 - AEGEAN AIRLINES</option>
<option value="A4">A4 - JSC AZIMUTH AIRLINES</option>
<option value="A5">A5 - HOP!</option>
<option value="A6">A6 - YUNNAN HONG TU AIRLINES</option>
<option value="A7">A7 - AEREO CALAFIA</option>
<option value="A8">A8 - AEROLINK UGANDA LIMITED</option>
<option value="A9">A9 - GEORGIAN AIRWAYS</option>
<option value="AA">AA - AMERICAN AIRLINES</option>
<option value="AB">AB - AIR BERLIN</option>
<option value="AC">AC - AIR CANADA</option>
<option value="AD">AD - AZUL LINHAS</option>
<option value="AE">AE - MANDARIN AIRLINES</option>
<option value="AF">AF - AIR FRANCE</option>
<option value="AG">AG - ARUBA AIRLINES</option>
<option value="AH">AH - AIR ALGERIE</option>
<option value="AI">AI - AIR INDIA</option>
<option value="AJ">AJ - AZTEC WORLDWIDE AIRLINES</option>
<option value="AK">AK - AIR ASIA</option>
<option value="AL">AL - AIR LEISURE</option>
<option value="AM">AM - AEROMÉXICO</option>
<option value="AN">AN - ADVANCED AIR</option>
<option value="AO">AO - AIR JUAN AVIATION</option>
<option value="AP">AP - AIR BLUE</option>
<option value="AQ">AQ - 9 AIR</option>
<option value="AR">AR - AEROLÍNEAS ARGENTINAS</option>
<option value="AS">AS - ALASKA AIRLINES</option>
<option value="AT">AT - ROYAL AIR MAROC</option>
<option value="AU">AU - Canada Jetlines </option>
<option value="AV">AV - AVIANCA</option>
<option value="AW">AW - AFRICA WORLD AIRLINES LIMITED</option>
<option value="AX">AX - TRANS STATES AIRLINES</option>
<option value="AY">AY - FINNAIR</option>
<option value="AZ">AZ - ITA Airways</option>
<option value="B0">B0 - LA COMPAGNIE</option>
<option value="B1">B1 - BRAVO PASSENGER SOLUTION</option>
<option value="B2">B2 - BELAVIA</option>
<option value="B3">B3 - BHUTAN AIRLINES</option>
<option value="B4">B4 - BEOND</option>
<option value="B5">B5 - EAST AFRICAN SAFARI AIR EXPRES</option>
<option value="B6">B6 - JETBLUE AIRWAYS</option>
<option value="B7">B7 - UNI AIRWAYS</option>
<option value="B8">B8 - ERITREAN AIRLINES</option>
<option value="B9">B9 - IRAN AIR TOURS</option>
<option value="BA">BA - BRITISH AIRWAYS</option>
<option value="BB">BB - SEABORNE AIRLINES</option>
<option value="BBO">BBO - FLYBABOO</option>
<option value="BC">BC - SKYMARK AIRLINES</option>
<option value="BD">BD - BMI</option>
<option value="BE">BE - FLYBE</option>
<option value="BF">BF - FRENCH BEE</option>
<option value="BG">BG - BIMAN BANGLADESH AIRLINE</option>
<option value="BI">BI - ROYAL BRUNEI</option>
<option value="BJ">BJ - NOUVELAIR TUNISIE</option>
<option value="BK">BK - OKAY AIRWAYS</option>
<option value="BL">BL - JETSTAR PACIFIC</option>
<option value="BM">BM - BMI REGIONAL</option>
<option value="BN">BN - Sky Alps</option>
<option value="BO">BO - BB AIRWAYS</option>
<option value="BP">BP - AIR BOTSWANA</option>
<option value="BQ">BQ - Aeromar Airlines</option>
<option value="BR">BR - EVA AIR</option>
<option value="BS">BS - US-BANGLA AIRLINES</option>
<option value="BT">BT - AIR BALTIC</option>
<option value="BU">BU - COMPAGNIE AFRICAINE D AVIATION</option>
<option value="BV">BV - TOKI AIR</option>
<option value="BW">BW - CARIBBEAN AIRLINES</option>
<option value="BX">BX - AIR BUSAN</option>
<option value="BY">BY - THOMSONFLY LTD</option>
<option value="BZ">BZ - BLUE BIRD AIRWAYS</option>
<option value="C0">C0 - ONE CARIBBEAN</option>
<option value="C1">C1 - TECTIMES SUDAMERICANA</option>
<option value="C2">C2 - CEIBA INTERCONTINENTAL</option>
<option value="C3">C3 - TRADE AIR</option>
<option value="C5">C5 - COMMUTAIR</option>
<option value="C6">C6 - My Freighter</option>
<option value="C7">C7 - CINNAMON AIR</option>
<option value="C8">C8 - CRONOSAIR</option>
<option value="C9">C9 - ALPHALAND AVIATION</option>
<option value="CA">CA - AIR CHINA</option>
<option value="CC">CC - CM AIRLINES</option>
<option value="CD">CD - CORENDON DUTCH AIRLINES</option>
<option value="CE">CE - CHALAIR AVIATION</option>
<option value="CF">CF - CIAF</option>
<option value="CG">CG - PNG AIR</option>
<option value="CH">CH - BEMIDJI AIRLINES</option>
<option value="CI">CI - CHINA AIRLINES</option>
<option value="CJ">CJ - BA CITY FLYER</option>
<option value="CK">CK - CHINA CARGO AIRLINES</option>
<option value="CL">CL - LUFTHANSA CITYLINE</option>
<option value="CM">CM - COPA AIRLINES</option>
<option value="CN">CN - GRAND CHINA AIR</option>
<option value="CO">CO - CONTINENTAL</option>
<option value="CP">CP - COMPASS</option>
<option value="CQ">CQ - COASTAL TRAVELS</option>
<option value="CR">CR - OAG WORLDWIDE</option>
<option value="CS">CS - Chair Airlines AG</option>
<option value="CT">CT - ALITALIA CITY LINER</option>
<option value="CU">CU - CUBANA DE AVIACION</option>
<option value="CV">CV - CARGOLUX AIRLINES INTERNATIONA</option>
<option value="CX">CX - CATHAY PACIFIC</option>
<option value="CY">CY - CYPRUS AIRWAYS</option>
<option value="CZ">CZ - CHINA SOUTHERN AIRLINES</option>
<option value="D2">D2 - SEVERSTAL</option>
<option value="D3">D3 - DAALLO AIRLINES</option>
<option value="D7">D7 - AIRASIA X</option>
<option value="D8">D8 - NORWEGIAN</option>
<option value="D9">D9 - DONAVIA</option>
<option value="DA">DA - AIR GEORGIA</option>
<option value="DB">DB - HOP BRIT AIR</option>
<option value="DC">DC - BRAATHENS REGIONAL</option>
<option value="DD">DD - NOK AIR</option>
<option value="DE">DE - CONDOR</option>
<option value="DF">DF - CONDOR BERLIN</option>
<option value="DG">DG - CEBGO</option>
<option value="DH">DH - DOUNIAH AIRLINES</option>
<option value="DI">DI - NORWEGIAN AIR UK</option>
<option value="DJ">DJ - AIRASIA JAPAN</option>
<option value="DK">DK - SUNCLASS AIRLINES</option>
<option value="DL">DL - DELTA AIR LINES</option>
<option value="DM">DM - ARAJET</option>
<option value="DN">DN - NORWEGIAN AIR ARGENTINA</option>
<option value="DO">DO - SKY HIGH AVIATION SERVICES</option>
<option value="DP">DP - POBEDA AIRLINES LLC</option>
<option value="DQ">DQ - DELTA CONNECTION</option>
<option value="DR">DR - RUILI AIRLINES</option>
<option value="DS">DS - EASYJET SWITZERLAND</option>
<option value="DT">DT - TAAG LINHAS</option>
<option value="DU">DU - SKY JET</option>
<option value="DV">DV - JSC AIRCOMPANY SCAT</option>
<option value="DW">DW - AERO-CHARTER</option>
<option value="DX">DX - DANISH AIR TRANSPORT</option>
<option value="DY">DY - NORWEGIAN AIR SHUTTLE</option>
<option value="DZ">DZ - DONGHAI AIRLINES</option>
<option value="E2">E2 - EUROWINGS EUROPE</option>
<option value="E3">E3 - NEW GEN</option>
<option value="E4">E4 - ENTERAIR</option>
<option value="E5">E5 - AIR ARABIA EGYPT</option>
<option value="E6">E6 - BRINGER AIR</option>
<option value="E7">E7 - EQUAFLIGHT</option>
<option value="E8">E8 - CITY AIRWAYS</option>
<option value="E9">E9 - IBEROJET</option>
<option value="EA">EA - Andalus</option>
<option value="EB">EB - WAMOS AIR</option>
<option value="EC">EC - OPENSKIES</option>
<option value="ED">ED - AIR EXPLORE</option>
<option value="EE">EE - REGIONAL JET</option>
<option value="EF">EF - FLY CAMINTER</option>
<option value="EG">EG - ERNEST AIRLINES</option>
<option value="EH">EH - ANA WINGS</option>
<option value="EI">EI - AER LINGUS</option>
<option value="EJ">EJ - NEW ENGLAND AIRLINES</option>
<option value="EK">EK - EMIRATES</option>
<option value="EL">EL - ELLINAIR</option>
<option value="EM">EM - EMPIRE AIRLINES</option>
<option value="EN">EN - AIR DOLOMITI</option>
<option value="EO">EO - PEGAS FLY</option>
<option value="EP">EP - ASEMAN AIRLINES</option>
<option value="EQ">EQ - TAME</option>
<option value="ER">ER - SERENE AIR</option>
<option value="ES">ES - ESTELAR</option>
<option value="ET">ET - ETHIOPIAN AIRLINES</option>
<option value="EU">EU - CHENGDU AIRLINES</option>
<option value="EV">EV - EXPRESSJET AIRLINES</option>
<option value="EW">EW - EUROWINGS</option>
<option value="EX">EX - XPRESS AIR</option>
<option value="EY">EY - ETIHAD AIRWAYS</option>
<option value="EZ">EZ - SUN AIR OF SCANDINAVIA</option>
<option value="F1">F1 - FARELOGIX</option>
<option value="F2">F2 - SAFARILINK</option>
<option value="F3">F3 - FLYADEAL</option>
<option value="F4">F4 - AIR FLAMENCO</option>
<option value="F6">F6 - FLY COMPASS SERVICE</option>
<option value="F7">F7 - DARWIN AIRLINE</option>
<option value="F8">F8 - FLAIR AIRLINES</option>
<option value="F9">F9 - FRONTIER AIRLINES</option>
<option value="FA">FA - SAFAIR</option>
<option value="FB">FB - BULGARIA AIR</option>
<option value="FBZ">FBZ - Flybondi</option>
<option value="FC">FC - FLY CORPORATE</option>
<option value="FCA">FCA - AIR2000</option>
<option value="FD">FD - THAI AIRASIA</option>
<option value="FE">FE - FAR EASTERN AIR</option>
<option value="FG">FG - ARIANA AFGHAN AIRLINES</option>
<option value="FH">FH - FREEBIRD AIRLINES</option>
<option value="FI">FI - ICELANDAIR</option>
<option value="FJ">FJ - FIJI AIRWAYS</option>
<option value="FL">FL - AIRTRAN AIRWAYS</option>
<option value="FLY">FLY - FLYME</option>
<option value="FM">FM - SHANGHAI AIRLINES</option>
<option value="FN">FN - FASTJET AIRLINES</option>
<option value="FO">FO - FLY BONDI</option>
<option value="FP">FP - PELICAN AIRLINES</option>
<option value="FR">FR - RYANAIR</option>
<option value="FS">FS - SYPHAX AIRLINES</option>
<option value="FT">FT - FLYEGYPT</option>
<option value="FU">FU - FUZHOU AIRLINES</option>
<option value="FUA">FUA - BUDGETAIR</option>
<option value="FV">FV - ROSSIYA AIRLINES</option>
<option value="FW">FW - IBEX AIRLINES</option>
<option value="FX">FX - FEDEX</option>
<option value="FY">FY - FIREFLY</option>
<option value="FZ">FZ - FLYDUBAI</option>
<option value="G2">G2 - GUINEA AIRLINES</option>
<option value="G3">G3 - GOL LINHAS AEREAS</option>
<option value="G4">G4 - ALLEGIANT AIR</option>
<option value="G5">G5 - CHINA EXPRESS AIRLINES</option>
<option value="G6">G6 - ANGKOR AIRWAYS</option>
<option value="G7">G7 - GOJET AIRLINES</option>
<option value="G8">G8 - GO AIR</option>
<option value="G9">G9 - AIR ARABIA</option>
<option value="GA">GA - GARUDA INDONESIA</option>
<option value="GC">GC - GLOBAL FEEDER</option>
<option value="GE">GE - TRANSASIA AIRWAYS</option>
<option value="GF">GF - GULF AIR</option>
<option value="GH">GH - GLOBUS</option>
<option value="GI">GI - ITEK AIR</option>
<option value="GJ">GJ - ZHEJIANG LOONG AIRLINES</option>
<option value="GK">GK - JETSTAR JAPAN</option>
<option value="GL">GL - AIR GREENLAND</option>
<option value="GM">GM - GERMANIA FLUG AG</option>
<option value="GP">GP - APG AIRLINES</option>
<option value="GQ">GQ - SKY EXPRESS</option>
<option value="GR">GR - AURIGNY AIR SERVICES</option>
<option value="GS">GS - TIANJIN AIRLINES</option>
<option value="GSM">GSM - TIANJIN AIRLINES</option>
<option value="GT">GT - AIR GUILIN</option>
<option value="GU">GU - AVIATECA</option>
<option value="GV">GV - GRANTAVIATION</option>
<option value="GW">GW - SKYGREECE AIRLINES</option>
<option value="GX">GX - GUANGXI BEIBU GULF AIRLINES</option>
<option value="GY">GY - COLORFUL GUIZHOU AIRLINE</option>
<option value="GZ">GZ - AIR RAROTONGA</option>
<option value="H1">H1 - HAHN AIR</option>
<option value="H2">H2 - SKY AIRLINE</option>
<option value="H3">H3 - HERMES AIRLINES</option>
<option value="H4">H4 - Hisky</option>
<option value="H6">H6 - BULGARIAN AIR CHARTER</option>
<option value="H7">H7 - TARON AVIA</option>
<option value="H8">H8 - SKY AIRLINES PERU</option>
<option value="H9">H9 - HIMALAYA AIRLINES</option>
<option value="HA">HA - HAWAIIAN AIRLINES</option>
<option value="HB">HB - GREATER BAY AIRLINES</option>
<option value="HC">HC - AIR SENEGAL</option>
<option value="HD">HD - AIRDO</option>
<option value="HE">HE - LGW LUFTFAHRTGES WALTER</option>
<option value="HF">HF - AIR COTE DIVOIRE</option>
<option value="HG">HG - NIKI LUFTFAHRT</option>
<option value="HH">HH - TABAN AIR</option>
<option value="HI">HI - PAPILLON AIRWAYS</option>
<option value="HJ">HJ - HELLAS JET</option>
<option value="HK">HK - SKIPPERS AVIATION PTY</option>
<option value="HM">HM - AIR SEYCHELLES</option>
<option value="HN">HN - SAFFAT AIRLINES</option>
<option value="HO">HO - JUNEYAO AIRLINES</option>
<option value="HP">HP - AMAPOLA FLYG AB</option>
<option value="HQ">HQ - THOMAS COOK AIRLINES</option>
<option value="HR">HR - HAHN AIR</option>
<option value="HS">HS - SVENSKA DIREKTFLYG</option>
<option value="HU">HU - HAINAN AIRLINES</option>
<option value="HV">HV - TRANSAVIA</option>
<option value="HW">HW - NORTH WRIGHT AIR</option>
<option value="HX">HX - HONG KONG AIRLINES</option>
<option value="HY">HY - UZBEKISTAN AIRWAYS</option>
<option value="HZ">HZ - AURORA AIRLINES</option>
<option value="I1">I1 - CTS VIAGGI</option>
<option value="I2">I2 - IBERIA EXPRESS</option>
<option value="I3">I3 - ATA AIRLINES</option>
<option value="I4">I4 - I FLY</option>
<option value="I5">I5 - AIRASIA INDIA</option>
<option value="I6">I6 - AIR INDUS</option>
<option value="I7">I7 - INTER ILES AIR</option>
<option value="I8">I8 - IZHAVIA</option>
<option value="I9">I9 - China Central Airlines</option>
<option value="IA">IA - IRAQI AIRWAYS</option>
<option value="IB">IB - IBERIA</option>
<option value="IC">IC - NACIL INDIAN AIRLINE</option>
<option value="ID">ID - BATIK AIR</option>
<option value="IE">IE - SOLOMON AIRLINES</option>
<option value="IF">IF - Fly Baghdad</option>
<option value="IG">IG - AIR ITALY</option>
<option value="IH">IH - IRTYSH AIR</option>
<option value="II">II - IBC AIRWAYS</option>
<option value="IJ">IJ - SPRING AIRLINES JAPAN</option>
<option value="IK">IK - AIR KIRIBATI</option>
<option value="IL">IL - PT.TRIGANA AIR SERVICE</option>
<option value="IN">IN - NAM AIR</option>
<option value="IO">IO - IRAERO</option>
<option value="IQ">IQ - QAZAQ AIR</option>
<option value="IR">IR - IRAN AIR</option>
<option value="IS">IS - AIS AIRLINES B.V.</option>
<option value="IT">IT - TIGERAIR TAIWAN</option>
<option value="IU">IU - SUPERAIRJET</option>
<option value="IV">IV - CARDIFF AIRLINES</option>
<option value="IW">IW - WINGS AIR</option>
<option value="IX">IX - AIR INDIA CHARTERS LIMITED</option>
<option value="IY">IY - YEMEN AIRWAYS</option>
<option value="IZ">IZ - ARKIA-ISRAELI AIRLINES LTD</option>
<option value="J0">J0 - RUTAIR LIMITED</option>
<option value="J2">J2 - AZERBAIJAN HAVA YOLLARY</option>
<option value="J3">J3 - NORTHWESTERN AIR</option>
<option value="J4">J4 - BADR AIRLINES</option>
<option value="J5">J5 - ALASKA SEAPLANE</option>
<option value="J6">J6 - JAMAICA AIR SHUTTLE</option>
<option value="J7">J7 - AFRIJET BUSINESS SERVICE</option>
<option value="J8">J8 - BERJAYA AIR</option>
<option value="J9">J9 - JAZEERA AIRWAYS</option>
<option value="JA">JA - JETSMART</option>
<option value="JB">JB - HELIJET INTERNATIONAL</option>
<option value="JC">JC - JAPAN AIR COMMUTER</option>
<option value="JD">JD - BEIJING CAPITAL AIRLINES</option>
<option value="JE">JE - MANGO</option>
<option value="JF">JF - JET ASIA</option>
<option value="JG">JG - AIRLINE CONTAINER</option>
<option value="JH">JH - FUJI DREAM AIRLINES</option>
<option value="JI">JI - MERAJ AIR</option>
<option value="JJ">JJ - LATAM LINHAS BRASIL</option>
<option value="JK">JK - SPANAIR</option>
<option value="JL">JL - JAPAN AIRLINES</option>
<option value="JM">JM - JAMBOJET</option>
<option value="JN">JN - JOON</option>
<option value="JO">JO - JETTIME</option>
<option value="JP">JP - ADRIA AIRWAYS</option>
<option value="JQ">JQ - JETSTAR AIRWAYS</option>
<option value="JR">JR - JOY AIR</option>
<option value="JS">JS - AIR KORYO</option>
<option value="JT">JT - LION AIRLINES</option>
<option value="JU">JU - AIR SERBIA</option>
<option value="JV">JV - BEARSKIN LAKE AIR SERVICES</option>
<option value="JW">JW - VANILLA AIR</option>
<option value="JX">JX - STARLUX</option>
<option value="JXX">JXX - ICELAND EXPRESS</option>
<option value="JY">JY - INTERCARIBBEAN AIRWAYS</option>
<option value="JZ">JZ - JUBBA AIRWAYS</option>
<option value="K2">K2 - EUROLOT</option>
<option value="K3">K3 - TAQUAN AIR SERVICES</option>
<option value="K4">K4 - ALS LTD</option>
<option value="K5">K5 - SILVERSTONE AIR SERVICES</option>
<option value="K6">K6 - CAMBODIA ANGKOR AIR</option>
<option value="K7">K7 - AIR KBZ</option>
<option value="K8">K8 - KAN AIR</option>
<option value="KA">KA - CATHAY DRAGON</option>
<option value="KB">KB - DRUK AIR</option>
<option value="KC">KC - AIR ASTANA</option>
<option value="KD">KD - KALSTAR AVIATION</option>
<option value="KE">KE - KOREAN AIR</option>
<option value="KF">KF - AIR BELGIUM</option>
<option value="KG">KG - KEY LIME AIR CORPORATION</option>
<option value="KH">KH - ALOHA AIR CARGO</option>
<option value="KI">KI - KRASAVIA</option>
<option value="KJ">KJ - AIR INCHEON</option>
<option value="KK">KK - ATLASJET AIRLINES</option>
<option value="KL">KL - KLM</option>
<option value="KM">KM - AIR MALTA</option>
<option value="KN">KN - CHINA UNITED AIRLINES</option>
<option value="KO">KO - OJSC KOMIAVIATRANS</option>
<option value="KP">KP - ASKY</option>
<option value="KQ">KQ - KENYA AIRWAYS</option>
<option value="KR">KR - CAMBODIA AIRWAYS</option>
<option value="KS">KS - AIR CONNECT </option>
<option value="KT">KT - SIAVIA</option>
<option value="KU">KU - KUWAIT AIRWAYS</option>
<option value="KV">KV - SKY REGIONAL AIRLINES</option>
<option value="KW">KW - KHARKIV AIRLINES</option>
<option value="KX">KX - CAYMAN AIRWAYS</option>
<option value="KY">KY - KUNMING AIRLINES</option>
<option value="L1">L1 - LUFTHANSA SYSTEM</option>
<option value="L4">L4 - GRUPO LASA</option>
<option value="L5">L5 - ATLANTIQUE AIR ASSISTANCE</option>
<option value="L6">L6 - MAURITANIA AIRLINES</option>
<option value="L8">L8 - AFRIC AVIATION</option>
<option value="L9">L9 - LUMIWINGS</option>
<option value="LA">LA - LATAM</option>
<option value="LC">LC - EQUATORIAL CONGO AIRLINE</option>
<option value="LE">LE - NORWEGIAN AIR SWEDEN AB</option>
<option value="LF">LF - CONTOUR AIRLINES</option>
<option value="LG">LG - LUXAIR</option>
<option value="LH">LH - LUFTHANSA</option>
<option value="LI">LI - LIAT</option>
<option value="LJ">LJ - JIN AIR</option>
<option value="LK">LK - LAO SKYWAY</option>
<option value="LL">LL - MIAMI AIR INTERNATIONAL</option>
<option value="LM">LM - LOGANAIR</option>
<option value="LN">LN - LIBYAN ARAB AIRLINES</option>
<option value="LO">LO - LOT POLISH AIRLINES</option>
<option value="LP">LP - LAN PERU</option>
<option value="LQ">LQ - LANMEI AIRLINES</option>
<option value="LR">LR - LACSA</option>
<option value="LS">LS - JET2</option>
<option value="LT">LT - LONGJIANG AIRLINES</option>
<option value="LU">LU - LATAM AIRLINES CHILE</option>
<option value="LV">LV - OPEN SKIES</option>
<option value="LW">LW - LATIN AMERICAN WINGS</option>
<option value="LX">LX - SWISS INT. AIR LINES</option>
<option value="LY">LY - EL AL ISRAEL AIRLINES</option>
<option value="LZ">LZ - SWISS GLOBAL AIR LINES</option>
<option value="M0">M0 - AERO MONGOLIA</option>
<option value="M2">M2 - MHS AVIATION</option>
<option value="M3">M3 - NORTH FLYING AS</option>
<option value="M4">M4 - MISTRAL AIR</option>
<option value="M5">M5 - KENMORE AIR</option>
<option value="M8">M8 - SKYJET</option>
<option value="M9">M9 - MOTOR-SICH JSC</option>
<option value="MA">MA - MALEV</option>
<option value="MB">MB - MNG AIRLINES CARGO</option>
<option value="MC">MC - AIR MOBILITY COMMAND</option>
<option value="MD">MD - AIR MADAGASCAR</option>
<option value="ME">ME - MIDDLE EAST AIRLINES</option>
<option value="MF">MF - XIAMENAIR</option>
<option value="MG">MG - EZNIS AIRWAYS</option>
<option value="MH">MH - MALAYSIA AIRLINES</option>
<option value="MI">MI - SILKAIR</option>
<option value="MJ">MJ - MYWAY AIRLINES</option>
<option value="MK">MK - AIR MAURITIUS</option>
<option value="ML">ML - AIR MEDITERRANEE</option>
<option value="MM">MM - PEACH AVIATION</option>
<option value="MN">MN - COMAIR KULULA.COM</option>
<option value="MO">MO - CALM AIR INTERNATIONAL</option>
<option value="MP">MP - MARTINAIR</option>
<option value="MQ">MQ - ENVOY AIR</option>
<option value="MR">MR - HUNNU AIR</option>
<option value="MS">MS - EGYPTAIR</option>
<option value="MT">MT - THOMAS COOK AIRLINES</option>
<option value="MU">MU - CHINA EASTERN AIRLINES</option>
<option value="MV">MV - AIR MEDITERRANEAN</option>
<option value="MW">MW - MOKULELE FLIGHT SERVICES</option>
<option value="MX">MX - MEXICANA DE AVIACION</option>
<option value="MY">MY - MASWINGS</option>
<option value="MZ">MZ - AMAKUSA AIRLINES</option>
<option value="N0">N0 - Norse Atlantic Airways</option>
<option value="N3">N3 - AEROLIEAS MAS</option>
<option value="N4">N4 - NORD WIND</option>
<option value="N5">N5 - NOLINOR</option>
<option value="N6">N6 - NOMAD AVIATION</option>
<option value="N7">N7 - NORDIC REGIONAL AIRLINES</option>
<option value="N9">N9 - SHREE AIRLINES</option>
<option value="NA">NA - NESMA AIRLINES</option>
<option value="NB">NB - SKYPOWER EXPRESS</option>
<option value="ND">ND - FMI AIR</option>
<option value="NE">NE - SKYEUROPE</option>
<option value="NF">NF - AIR VANUATU</option>
<option value="NG">NG - AL NASER WINGS</option>
<option value="NH">NH - ALL NIPPON AIRWAYS ANA</option>
<option value="NI">NI - PORTUGALIA</option>
<option value="NJ">NJ - AERO VIP</option>
<option value="NK">NK - SPIRIT AIRLINES</option>
<option value="NL">NL - SHAHEEN AIR</option>
<option value="NM">NM - ASMAN AIRLINES</option>
<option value="NN">NN - VIM AIRLINES</option>
<option value="NO">NO - NEOS</option>
<option value="NP">NP - NILE AIR</option>
<option value="NQ">NQ - AIR JAPAN COMPANY LTD</option>
<option value="NS">NS - HEBEI AIRLINE</option>
<option value="NT">NT - BINTER CANARIAS</option>
<option value="NU">NU - JAPAN TRANSOCEAN AIR</option>
<option value="NV">NV - KARUN AIRLINES</option>
<option value="NW">NW - NORTHWEST</option>
<option value="NX">NX - AIR MACAU</option>
<option value="NY">NY - AIR ICELAND</option>
<option value="NZ">NZ - AIR NEW ZEALAND</option>
<option value="O2">O2 - LINEAR AIR</option>
<option value="O4">O4 - ANTRAK AIR</option>
<option value="O5">O5 - COMORES AVIATION</option>
<option value="O6">O6 - AVIANCA BRAZIL</option>
<option value="O7">O7 - SUE ORENBURG REGION</option>
<option value="O8">O8 - SIAM AIR TRANSPORT</option>
<option value="O9">O9 - NOVA AIRWAYS</option>
<option value="OA">OA - OLYMPIC AIR</option>
<option value="OB">OB - BOLIVIANA DE AVIACION BOA</option>
<option value="OC">OC - ORIENTAL AIR BRIDGE CO LTD</option>
<option value="OD">OD - MALINDO AIRWAYS</option>
<option value="OE">OE - LAUDAMOTION</option>
<option value="OG">OG - FLY PLAY </option>
<option value="OH">OH - PSA AIRLINES</option>
<option value="OI">OI - HINTERLAND AVIATION</option>
<option value="OK">OK - CZECH AIRLINES</option>
<option value="OL">OL - SAMOA AIRWAYS</option>
<option value="OM">OM - MIAT MONGOLIAN AIRLINES</option>
<option value="ON">ON - NAURU AIRLINES</option>
<option value="OO">OO - SKYWEST AIRLINES</option>
<option value="OP">OP - DAC INTERNATIONAL</option>
<option value="OQ">OQ - CHONGQING AIRLINES</option>
<option value="OR">OR - TUI FLY NETHERLANDS</option>
<option value="OS">OS - AUSTRIAN AIRLINES</option>
<option value="OT">OT - TCHADIA AIRLINES</option>
<option value="OU">OU - CROATIA AIRLINES</option>
<option value="OV">OV - SALAM AIR</option>
<option value="OV2">OV2 - SALAM AIR</option>
<option value="OW">OW - SKYWARD EXPRESS</option>
<option value="OX">OX - ORIENT THAI AIRLINES</option>
<option value="OY">OY - ANDES</option>
<option value="OZ">OZ - ASIANA AIRLINES</option>
<option value="P0">P0 - PROFLIGHT COMMUTER SERVICES</option>
<option value="P1">P1 - PUBLIC CHARTERS</option>
<option value="P2">P2 - AIR KENYA EXPRESS</option>
<option value="P3">P3 - PASSAREDO LINHAS</option>
<option value="P4">P4 - AIR PEACE</option>
<option value="P5">P5 - WINGO</option>
<option value="P6">P6 - PASCAN AVIATION</option>
<option value="P7">P7 - SMALL PLANET</option>
<option value="P8">P8 - SPRINTAIR</option>
<option value="P9">P9 - PERUVIAN AIRLINES</option>
<option value="PA">PA - AIRBLUE</option>
<option value="PB">PB - PAL AIRLINES</option>
<option value="PC">PC - PEGASUS</option>
<option value="PD">PD - PORTER AIRLINES</option>
<option value="PE">PE - PEOPLES</option>
<option value="PF">PF</option>
<option value="PG">PG - BANGKOK AIRWAYS</option>
<option value="PI">PI - POLAR AIRLINES</option>
<option value="PJ">PJ - AIR ST PIERRE</option>
<option value="PK">PK - PAKISTAN INTERNATIONAL</option>
<option value="PL">PL - SOUTHERN AIR CHARTER</option>
<option value="PM">PM - CANARY FLY</option>
<option value="PN">PN - CHINA WEST AIR</option>
<option value="PP">PP - JET AVIATION BUSINESS</option>
<option value="PQ">PQ - SKYUP AIRLINES</option>
<option value="PR">PR - PHILIPPINE AIRLINES</option>
<option value="PS">PS - UKRAINE INTERNATIONAL</option>
<option value="PT">PT - PIEDMONT AIRLINES</option>
<option value="PU">PU - PLUS ULTRA LINEAS AEREAS</option>
<option value="PV">PV - SAINT BARTH COMMUTER</option>
<option value="PW">PW - PRECISION AIR</option>
<option value="PX">PX - AIR NIUGINI</option>
<option value="PY">PY - SURINAM AIRWAYS</option>
<option value="PZ">PZ - LATAM AIRLINES PARAGUAY</option>
<option value="Q2">Q2 - MALDIVIAN</option>
<option value="Q3">Q3 - ANGUILLA AIR SERVICES</option>
<option value="Q4">Q4 - EUROAIRLINES</option>
<option value="Q5">Q5 - 40-MILE AIR</option>
<option value="Q6">Q6 - VOLARIS COSTA RICA</option>
<option value="Q7">Q7 - SKYBAHAMAS AIRLINES</option>
<option value="Q8">Q8 - TRANS AIR CONGO</option>
<option value="Q9">Q9 - WATANIYA AIRWAYS</option>
<option value="QB">QB - QESHM AIRLINE</option>
<option value="QC">QC - CAMAIR CO</option>
<option value="QD">QD - JC CAMBODIA AIRLINES</option>
<option value="QF">QF - QANTAS</option>
<option value="QG">QG - CITILINK INDONESIA</option>
<option value="QH">QH - BAMBOO AIRWAYS</option>
<option value="QI">QI - CIMBER AIR</option>
<option value="QK">QK - JAZZ AVIATION</option>
<option value="QL">QL - LASER AIRLINES</option>
<option value="QM">QM - MONACAIR</option>
<option value="QN">QN - SKYTRANS</option>
<option value="QP">QP - AIRKENYA</option>
<option value="QQ">QQ - ALLIANCE AIRLINES</option>
<option value="QR">QR - QATAR AIRWAYS</option>
<option value="QS">QS - SMARTWINGS</option>
<option value="QT">QT - TAMPA CARGO</option>
<option value="QU">QU - UTAIR - UKRAINE</option>
<option value="QV">QV - LAO AIRLINES</option>
<option value="QW">QW - QINGDAO AIRLINE</option>
<option value="QX">QX - HORIZON AIR</option>
<option value="QY">QY - EUROPEAN AIR TRANSPORT</option>
<option value="QZ">QZ - PT INDONESIA AIRASIA</option>
<option value="R0">R0 - TANTALUS AIR</option>
<option value="R2">R2 - GROUPE TRANSAIR</option>
<option value="R3">R3 - YAKUTIA JSC AIRCOMPANY</option>
<option value="R4">R4 - STATE TRANS CO OF RUSSIA</option>
<option value="R5">R5 - JORDAN AVIATION</option>
<option value="R6">R6 - DOT LT</option>
<option value="R7">R7 - ASERCA AIRLINES</option>
<option value="R9">R9 - CAMAI AIR</option>
<option value="RA">RA - NEPAL AIRLINES</option>
<option value="RB">RB - SYRIAN ARAB AIRLINES</option>
<option value="RC">RC - ATLANTIC AIRWAYS</option>
<option value="RE">RE - STOBART AIR</option>
<option value="RG">RG - ROTANA JET</option>
<option value="RI">RI - RAHILA AIR</option>
<option value="RJ">RJ - ROYAL JORDANIAN</option>
<option value="RK">RK - RYANAIR UK</option>
<option value="RM">RM - AIRCOMPANY ARMENIA</option>
<option value="RN">RN - ESWATINI AIR</option>
<option value="RO">RO - TAROM</option>
<option value="RP">RP - BUDAPEST AIRCRAFT SERVICE</option>
<option value="RQ">RQ - KAM AIR</option>
<option value="RR">RR - ROYAL AIR FORCE</option>
<option value="RS">RS - AIR SEOUL</option>
<option value="RT">RT - JSC UVT AERO</option>
<option value="RU">RU - AIR BRIDGE CARGO</option>
<option value="RV">RV - AIR CANADA ROUGE</option>
<option value="RW">RW - ROYAL AIR CHARTER SERVICE</option>
<option value="RX">RX - REGENT AIRWAYS</option>
<option value="RY">RY - JIANGXI AIR</option>
<option value="RZ">RZ - SANSA</option>
<option value="S0">S0 - AEROLINEAS SOSA</option>
<option value="S1">S1 - LUFTHANSA SYSTEMS</option>
<option value="S2">S2 - JET LITE</option>
<option value="S3">S3 - SANTA BARBARA AIRLINES</option>
<option value="S4">S4 - SATA INTERNATIONAL</option>
<option value="S5">S5 - STAR AIR</option>
<option value="S6">S6 - SUNRISE AIRWAYS</option>
<option value="S7">S7 - S7 AIRLINES</option>
<option value="S8">S8 - SOUNDS AIR</option>
<option value="S9">S9 - TRI STATE CHARTER</option>
<option value="SA">SA - SOUTH AFRICAN AIRWAYS</option>
<option value="SB">SB - AIRCALIN</option>
<option value="SC">SC - SHANDONG AIRLINES</option>
<option value="SD">SD - SUDAN AIRWAYS</option>
<option value="SDR">SDR - SUNDAIR GMBH</option>
<option value="SE">SE - XL AIRWAYS</option>
<option value="SF">SF - TASSILI AIRLINES</option>
<option value="SG">SG - SPICEJET</option>
<option value="SH">SH - SHARP AIRLINES</option>
<option value="SI">SI - BLUE ISLAND</option>
<option value="SJ">SJ - SRIWIJAYA AIR</option>
<option value="SK">SK - SAS SCANDINAVIAN</option>
<option value="SKY">SKY - SKY EUROPE AIRLINES</option>
<option value="SL">SL - THAI LION AIR</option>
<option value="SM">SM - AIR CAIRO</option>
<option value="SN">SN - BRUSSELS AIRLINES</option>
<option value="SO">SO - APEX AIRLINE</option>
<option value="SP">SP - SATA AIR ACORES</option>
<option value="SQ">SQ - SINGAPORE AIRLINES</option>
<option value="SR">SR - SUNDAIR</option>
<option value="SS">SS - CORSAIR</option>
<option value="ST">ST - GERMANIA FLUGGESELLSCHAFT</option>
<option value="SU">SU - AEROFLOT</option>
<option value="SV">SV - SAUDIA</option>
<option value="SW">SW - AIR NAMIBIA</option>
<option value="SX">SX - SKYWORK AIRLINES</option>
<option value="SY">SY - SUN COUNTRY</option>
<option value="SZ">SZ - SOMON AIR</option>
<option value="T0">T0 - TACA PERU</option>
<option value="T1">T1 - Tigerair Australia</option>
<option value="T2">T2 - FLY ART</option>
<option value="T3">T3 - EASTERN AIRWAYS</option>
<option value="T4">T4 - TRIP LINHAS AEREAS</option>
<option value="T5">T5 - TURKMENISTAN AIRLINES</option>
<option value="T6">T6 - AirSWIFT</option>
<option value="T7">T7 - TWIN JET</option>
<option value="T8">T8 - GROZNYY AVIA</option>
<option value="T9">T9 - TURPIAL AIRLINES</option>
<option value="TA">TA - TACA INTL AIRLINES</option>
<option value="TB">TB - TUI FLY BELGIUM</option>
<option value="TC">TC - AIR TANZANIA</option>
<option value="TD">TD - ATLANTIS EUROPEAN AIRWAY</option>
<option value="TE">TE - SKY TAXI</option>
<option value="TF">TF - BRAATHENS REGIONAL AVIATION AB</option>
<option value="TG">TG - THAI AIRWAYS</option>
<option value="TI">TI - TROPIC OCEANAIRWAYS</option>
<option value="TJ">TJ - TRADEWIND AVIATION</option>
<option value="TK">TK - TURKISH AIRLINES</option>
<option value="TL">TL - AIRNORTH REGIONAL</option>
<option value="TM">TM - LAM MOZAMBIQUE</option>
<option value="TN">TN - AIR TAHITI NUI</option>
<option value="TO">TO - TRANSAVIA FRANCE</option>
<option value="TO3">TO3 - TRANSAVIA</option>
<option value="TOM">TOM - THOMSONFLY</option>
<option value="TP">TP - TAP PORTUGAL</option>
<option value="TQ">TQ - TANDEM AERO</option>
<option value="TR">TR - SCOOT TIGERAIR</option>
<option value="TS">TS - AIR TRANSAT</option>
<option value="TT">TT - TIGERAIR AUSTRALIA</option>
<option value="TU">TU - TUNISAIR</option>
<option value="TV">TV - TIBET AIRLINES</option>
<option value="TW">TW - T WAY AIR</option>
<option value="TX">TX - AIR CARAIBES</option>
<option value="TY">TY - AIR CALEDONIE</option>
<option value="TZ">TZ - TSARADIA</option>
<option value="U2">U2 - EASYJET AIRLINE</option>
<option value="U4">U4 - BUDDHA AIR</option>
<option value="U5">U5 - KARINOU AIRLINES</option>
<option value="U6">U6 - URAL AIRLINES</option>
<option value="U7">U7 - AIR UGANDA</option>
<option value="U8">U8 - ARMAVIA</option>
<option value="U9">U9 - UNILODE AVIATION</option>
<option value="UA">UA - UNITED</option>
<option value="UB">UB - MYANMAR AIRWAYS INTL</option>
<option value="UC">UC - LAN CHILE CARGO</option>
<option value="UD">UD - UR Airlines</option>
<option value="UE">UE - ULTIMATE JETCHARTERS</option>
<option value="UF">UF - UKRAINIAN MEDITERRANEAN</option>
<option value="UG">UG - TUNINTER</option>
<option value="UH">UH - ATLASJET UKRAINE</option>
<option value="UI">UI - AURIC AIR</option>
<option value="UJ">UJ - ALMASRIA UNIVERSAL</option>
<option value="UK">UK - VISTARA</option>
<option value="UL">UL - SRILANKAN AIRLINES</option>
<option value="UM">UM - AIR ZIMBABWE</option>
<option value="UN">UN - TRANSAERO AIRLINES</option>
<option value="UO">UO - HK EXPRESS</option>
<option value="UP">UP - BAHAMASAIR</option>
<option value="UQ">UQ - URUMQI AIRLINES</option>
<option value="UR">UR - UGANDA AIRLINES</option>
<option value="US">US - US AIRWAYS</option>
<option value="UT">UT - UTAIR AVIATION</option>
<option value="UU">UU - AIR AUSTRAL</option>
<option value="UV">UV - HELICOPTEROS DEL SURESTE</option>
<option value="UX">UX - AIR EUROPA</option>
<option value="UY">UY - SKY PRIME CHARTER</option>
<option value="UZ">UZ - BURAQ AIR</option>
<option value="V0">V0 - CONVIASA</option>
<option value="V2">V2 - VISION AIRLINES</option>
<option value="V3">V3 - CARPATAIR</option>
<option value="V4">V4 - VIEQUWS AIR LINK</option>
<option value="V5">V5 - AEROVIAS DAP</option>
<option value="V6">V6 - VI AIR LINK</option>
<option value="V7">V7 - VOLOTEA</option>
<option value="V8">V8 - ILIAMNA AIR</option>
<option value="V9">V9 - VAN AIR EUROPE</option>
<option value="VA">VA - VIRGIN AUSTRALIA</option>
<option value="VB">VB - VIVAAEROBUS</option>
<option value="VC">VC - VIA AIRLINES</option>
<option value="VE">VE - EASYFLY S.A</option>
<option value="VF">VF - AJET</option>
<option value="VG">VG - VLM</option>
<option value="VH">VH - VIVA COLOMBIA</option>
<option value="VI">VI - VOLGA DNEPR</option>
<option value="VJ">VJ - VIETJET AVIATION</option>
<option value="VK">VK - LEVEL</option>
<option value="VL">VL - MED-VIEW AIRLINE</option>
<option value="VM">VM - MAX AIR LIMITED</option>
<option value="VN">VN - VIETNAM AIRLINES</option>
<option value="VO">VO - VLM AIRLINES</option>
<option value="VP">VP - FLYME</option>
<option value="VQ">VQ - NOVOAIR</option>
<option value="VR">VR - TRANSPORTES AEREOS DE CABO VER</option>
<option value="VS">VS - VIRGIN ATLANTIC</option>
<option value="VT">VT - AIR TAHITI</option>
<option value="VU">VU - AIR IVOIRE</option>
<option value="VV">VV - VIVA AIR PERU</option>
<option value="VW">VW - AEROMAR</option>
<option value="VX">VX - VIRGIN AMERICA</option>
<option value="VY">VY - VUELING AIRLINES</option>
<option value="VZ">VZ - THAI VIETJET AIR</option>
<option value="W1">W1 - W1</option>
<option value="W2">W2 - FLEXFLIGHT</option>
<option value="W3">W3 - ARIK AIR</option>
<option value="W4">W4 - Wizz Air Malta</option>
<option value="W5">W5 - MAHAN AIRLINES</option>
<option value="W6">W6 - WIZZ AIR</option>
<option value="W7">W7 - Wings of Lebanon</option>
<option value="W9">W9 - WIZZ AIR UK</option>
<option value="WA">WA - KLM CITYHOPPER</option>
<option value="WB">WB - RWANDAIR</option>
<option value="WC">WC - ISLENA DE INVERSIONES</option>
<option value="WD">WD - WDL AVIATION</option>
<option value="WE">WE - THAI SMILE AIRWAYS</option>
<option value="WF">WF - WIDEROES</option>
<option value="WG">WG - SUNWING AIRLINES</option>
<option value="WH">WH - WDL AVIATION</option>
<option value="WI">WI - WHITE AIRWAYS</option>
<option value="WJ">WJ - JETSMART AIRLINES</option>
<option value="WK">WK - EDELWEISS AIR AG</option>
<option value="WM">WM - WINDWARD ISLAND AIRWAYS</option>
<option value="WN">WN - SOUTHWEST AIRLINES</option>
<option value="WO">WO - SWOOP</option>
<option value="WOW">WOW - WORLD AIRWAYS</option>
<option value="WP">WP - ISLAND AIR</option>
<option value="WR">WR - WESTJET ENCORE LTD</option>
<option value="WS">WS - WESTJET</option>
<option value="WT">WT - WASAYA AIRWAYS</option>
<option value="WU">WU - WIZZ AIR UKRAINE</option>
<option value="WV">WV - WESTAIR AVIATION</option>
<option value="WW">WW - WOW AIR</option>
<option value="WX">WX - CITYJET</option>
<option value="WY">WY - OMAN AIR</option>
<option value="WZ">WZ - RED WINGS AIRLINES</option>
<option value="X1">X1 - Hahn Air Technologies GmbH</option>
<option value="X2">X2 - CHINA XINHUA AIRLINES</option>
<option value="X3">X3 - TUIFLY GMBH</option>
<option value="X4">X4 - AIR EXCURSIONS</option>
<option value="X5">X5 - AIR EUROPA EXPRESS</option>
<option value="X6">X6 - ARC DUMMY</option>
<option value="X7">X7 - EXEC AIR</option>
<option value="X8">X8 - AIRMAX</option>
<option value="X9">X9 - AVION EXPRESS</option>
<option value="XC">XC - CORENDON AIRLINES</option>
<option value="XC3">XC3 - CORENDON AIRLINES</option>
<option value="XD">XD - ARC</option>
<option value="XE">XE - JETSUITEX</option>
<option value="XF">XF - MONGOLIAN AIRWAYS</option>
<option value="XG">XG - SUNEXPRESS GERMANY</option>
<option value="XH">XH - Spec. Grd Handl. Ser.</option>
<option value="XJ">XJ - THAI AIR ASIA X</option>
<option value="XK">XK - AIR CORSICA</option>
<option value="XL">XL - LATAM AIRLINES ECUADOR</option>
<option value="XN">XN - TRAVEL EXPRESS AVIATION</option>
<option value="XO">XO - SEAIR</option>
<option value="XP">XP - AVELO AIRLINES</option>
<option value="XQ">XQ - SUN EXPRESS</option>
<option value="XR">XR - CORENDON AIRLINES EUROPE</option>
<option value="XS">XS - SITA AIRLINES</option>
<option value="XT">XT - INDONESIA AIRASIA EXTRA</option>
<option value="XU">XU - AFRICAN EXPRESS AIRWAYS</option>
<option value="XV">XV - BVI AIRWAYS</option>
<option value="XW">XW - NOKSCOOT AIRLINE</option>
<option value="XY">XY - FLYNAS</option>
<option value="XZ">XZ - Aero Italia </option>
<option value="Y1">Y1 - TRAVEL TECHNOLOGY INTERACTIVE</option>
<option value="Y2">Y2 - AIR CENTURY</option>
<option value="Y3">Y3 - SKY KG AIRLINES</option>
<option value="Y4">Y4 - VOLARIS</option>
<option value="Y5">Y5 - GOLDEN MYANMAR</option>
<option value="Y6">Y6 - AB AVIATION</option>
<option value="Y7">Y7 - NORDSTAR</option>
<option value="Y8">Y8 - SUPARNA AIRLINES</option>
<option value="Y9">Y9 - KISH AIRLINES</option>
<option value="YA">YA - NEGO AIRLINE ONE</option>
<option value="YB">YB - Harbour Air Seaplanes</option>
<option value="YC">YC - YAMAL AIRLINES</option>
<option value="YD">YD - MAURITANIA AIRWAYS</option>
<option value="YE">YE - YANAIR</option>
<option value="YG">YG - SOUTH AIRLINES</option>
<option value="YH">YH - YANGON AIRWAYS</option>
<option value="YJ">YJ - ASIAN WINGS AIRWAYS</option>
<option value="YK">YK - AVIA TRAFFIC COMPANY</option>
<option value="YL">YL - LIBYAN WINGS</option>
<option value="YM">YM - MONTENEGRO AIRLINES</option>
<option value="YN">YN - AIR CREEBEC</option>
<option value="YO">YO - HELI AIR MONACO</option>
<option value="YP">YP - Air Premia</option>
<option value="YQ">YQ - TAR AEROLÍNEAS</option>
<option value="YR">YR - SCENIC AIRLINES</option>
<option value="YS">YS - HOP REGIONAL</option>
<option value="YT">YT - YETI AIRLINES</option>
<option value="YU">YU - EUROATLANTIC AIRWAYS</option>
<option value="YV">YV - MESA AIRLINES</option>
<option value="YW">YW - AIR NOSTRUM</option>
<option value="YX">YX - REPUBLIC AIRLINE</option>
<option value="YY">YY - ANY AIRLINE (IATA)</option>
<option value="YZ">YZ - ALAS URUGUAY</option>
<option value="Z0">Z0 - Norse Atlantic UK LTD</option>
<option value="Z2">Z2 - PHILIPPINES AIRASIA</option>
<option value="Z3">Z3 - PROMECH</option>
<option value="Z5">Z5 - GMG AIRLINES</option>
<option value="Z6">Z6 - DNIEPROAVIA</option>
<option value="Z7">Z7 - AMASZONAS URUGUAY</option>
<option value="Z8">Z8 - AMASZONAS</option>
<option value="Z9">Z9 - MYAIRLINES</option>
<option value="ZA">ZA - SKY ANGKOR AIRLINE</option>
<option value="ZB">ZB - AIR ALBANIA</option>
<option value="ZC">ZC - NU AERO LTD</option>
<option value="ZD">ZD - EWA AIR</option>
<option value="ZE">ZE - EASTAR JET</option>
<option value="ZF">ZF - AZUR AIR</option>
<option value="ZG">ZG - ZIP AIR </option>
<option value="ZH">ZH - SHENZEN AIRLINES</option>
<option value="ZI">ZI - AIGLE AZUR</option>
<option value="ZJ">ZJ - ZAMBEZI AIRLINES</option>
<option value="ZK">ZK - GREAT LAKES AVIATION</option>
<option value="ZL">ZL - REGIONAL EXPRESS</option>
<option value="ZM">ZM - AIR MANAS</option>
<option value="ZN">ZN - ZAMBIA AIRWAYS</option>
<option value="ZO">ZO - ZOOM AIR</option>
<option value="ZP">ZP - PARANAIR</option>
<option value="ZQ">ZQ - AZMAN AIR SERVICES</option>
<option value="ZR">ZR - PUNTO AZUL</option>
<option value="ZS">ZS - JSC KAZAVIASPAS</option>
<option value="ZT">ZT - TITAN AIRWAYS</option>
<option value="ZW">ZW - AIR WISCONSIN</option>
<option value="ZX">ZX - AIR GEORGIA</option>
<option value="ZY">ZY - CHINA AIR CARGO</option>
<option value="ZZ">ZZ - SERVICE AGGREGATOR</option>
<option value="ZZ110">ZZ110 - Bul Air</option>
<option value="ZZ119">ZZ119 - OLYMPUS AIRWAYS</option>
<option value="ZZ125">ZZ125 - SPOT REISEN</option>
<option value="ZZ18">ZZ18 - THALYS</option>
<option value="ZZ19">ZZ19 - Intercités</option>
<option value="ZZ192">ZZ192 - Flightlink</option>
<option value="ZZ50">ZZ50 - RENFE</option>
<option value="ZZ51">ZZ51 - BENE</option>
<option value="ZZ6">ZZ6 - TGV</option>
<option value="ZZ7">ZZ7 - InterCity Express</option>
<option value="ZZ79">ZZ79 - Air Excel</option>
<option value="ZZ83">ZZ83 - MOMBASA AIR SAFARI</option>
<option value="ZZ84">ZZ84 - Grumeti Air</option>
<option value="ZZ856">ZZ856 - Premier Airlines</option>
<option value="ZZ857">ZZ857 - 748 Air Services</option>
<option value="ZZ860">ZZ860 - Renegade Air</option>
<option value="ZZ862">ZZ862 - Prishtina Jet</option>
<option value="ZZ867">ZZ867 - TravelTime</option>
<option value="ZZ868">ZZ868 - Fly ALS</option>
<option value="ZZ871">ZZ871 - Marabu Airlines</option>
<option value="ZZ877">ZZ877 - Heron Aviation</option>
<option value="ZZ878">ZZ878 - Fly Air41 Airways</option>
<option value="ZZ90">ZZ90 - As Salaam Air</option>
<option value="ZZ908">ZZ908 - KlasJet</option>
<option value="ZZRE">ZZRE - RAILEUROPE</option>
