<?php

return [
    'SIN' => 'Singapore Changi (SIN)',
    'HKG' => 'Hong Kong International (HKG)',
    'LOS' => 'Murtala Muhammed International (LOS)',
    'ABV' => 'Nnamdi Azikiwe International (ABV)',
    'LHR' => 'London Heathrow (LHR)',
    'LGW' => 'London Gatwick (LGW)',
    'CDG' => 'Paris Charles de Gaulle (CDG)',
    'AMS' => 'Amsterdam Schiphol (AMS)',
    'DXB' => 'Dubai International (DXB)',
    'DOH' => 'Hamad International (DOH)',
    'JFK' => 'New York JFK (JFK)',
    'EWR' => 'Newark Liberty (EWR)',
    'LAX' => 'Los Angeles (LAX)',
    'SFO' => 'San Francisco (SFO)',
    'ORD' => "Chicago O'Hare (ORD)",
    'YYZ' => 'Toronto Pearson (YYZ)',
    'GRU' => 'São Paulo Guarulhos (GRU)',
    'CPT' => 'Cape Town (CPT)',
    'NBO' => 'Nairobi Jomo Kenyatta (NBO)',
    'ADD' => 'Addis Ababa Bole (ADD)',
    'DEL' => 'Delhi Indira Gandhi (DEL)',
    'BOM' => 'Mumbai Chhatrapati Shivaji (BOM)',
    'BKK' => 'Bangkok Suvarnabhumi (BKK)',
    'KUL' => 'Kuala Lumpur (KUL)',
    'ICN' => 'Seoul Incheon (ICN)',
    'NRT' => 'Tokyo Narita (NRT)',
    'HND' => 'Tokyo Haneda (HND)',
    'SYD' => 'Sydney Kingsford Smith (SYD)',
    'MEL' => 'Melbourne (MEL)',
];
